# Generated by Django 2.0.1 on 2020-10-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20201008_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='topic',
        ),
    ]
